use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct BootstrapStatic {
    pub events: Vec<Event>,
    pub game_settings: GameSettings,
    pub phases: Vec<Phase>,
    pub teams: Vec<Team>,
    pub total_players: u32,
    pub elements: Vec<Player>,
    pub element_stats: Vec<ElementStat>,
    pub element_types: Vec<ElementType>,
    pub chips: Vec<Chip>,
    pub game_config: Option<GameConfig>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Event {
    pub id: u32,
    pub name: String,
    pub deadline_time: String,
    pub release_time: Option<String>,
    pub average_entry_score: u32,
    pub finished: bool,
    pub data_checked: bool,
    pub highest_scoring_entry: Option<u32>,
    pub deadline_time_epoch: u64,
    pub deadline_time_game_offset: u32,
    pub highest_score: Option<u32>,
    pub is_previous: bool,
    pub is_current: bool,
    pub is_next: bool,
    pub cup_leagues_created: bool,
    pub h2h_ko_matches_created: bool,
    pub can_enter: bool,
    pub can_manage: bool,
    pub released: bool,
    pub ranked_count: u32,
    pub chip_plays: Vec<ChipPlay>,
    pub most_selected: Option<u32>,
    pub most_transferred_in: Option<u32>,
    pub top_element: Option<u32>,
    pub top_element_info: Option<TopElementInfo>,
    pub transfers_made: u32,
    pub most_captained: Option<u32>,
    pub most_vice_captained: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ChipPlay {
    pub chip_name: String,
    pub num_played: u32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct TopElementInfo {
    pub id: u32,
    pub points: u32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Team {
    pub code: u32,
    pub draw: u32,
    pub form: Option<String>,
    pub id: u32,
    pub loss: u32,
    pub name: String,
    pub played: u32,
    pub points: u32,
    pub position: u32,
    pub short_name: String,
    pub strength: u32,
    pub team_division: Option<serde_json::Value>,
    pub unavailable: bool,
    pub win: u32,
    pub strength_overall_home: u32,
    pub strength_overall_away: u32,
    pub strength_attack_home: u32,
    pub strength_attack_away: u32,
    pub strength_defence_home: u32,
    pub strength_defence_away: u32,
    pub pulse_id: u32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Player {
    pub chance_of_playing_next_round: Option<u32>,
    pub chance_of_playing_this_round: Option<u32>,
    pub code: u32,
    pub cost_change_event: i32,
    pub cost_change_event_fall: i32,
    pub cost_change_start: i32,
    pub cost_change_start_fall: i32,
    pub dreamteam_count: u32,
    pub element_type: u32,
    pub ep_next: String,
    pub ep_this: String,
    pub event_points: i32,
    pub first_name: String,
    pub form: String,
    pub id: u32,
    pub in_dreamteam: bool,
    pub news: String,
    pub news_added: Option<String>,
    pub now_cost: u32,
    pub photo: String,
    pub points_per_game: String,
    pub second_name: String,
    pub selected_by_percent: String,
    pub special: bool,
    pub squad_number: Option<u32>,
    pub status: String,
    pub team: u32,
    pub team_code: u32,
    pub total_points: i32,
    pub transfers_in: u32,
    pub transfers_in_event: u32,
    pub transfers_out: u32,
    pub transfers_out_event: u32,
    pub value_form: String,
    pub value_season: String,
    pub web_name: String,
    pub minutes: u32,
    pub goals_scored: u32,
    pub assists: u32,
    pub clean_sheets: u32,
    pub goals_conceded: u32,
    pub own_goals: u32,
    pub penalties_saved: u32,
    pub penalties_missed: u32,
    pub yellow_cards: u32,
    pub red_cards: u32,
    pub saves: u32,
    pub bonus: u32,
    pub bps: i32,
    pub influence: String,
    pub creativity: String,
    pub threat: String,
    pub ict_index: String,
    pub starts: u32,
    pub expected_goals: String,
    pub expected_assists: String,
    pub expected_goal_involvements: String,
    pub expected_goals_conceded: String,
    pub influence_rank: u32,
    pub influence_rank_type: u32,
    pub creativity_rank: u32,
    pub creativity_rank_type: u32,
    pub threat_rank: u32,
    pub threat_rank_type: u32,
    pub ict_index_rank: u32,
    pub ict_index_rank_type: u32,
    pub corners_and_indirect_freekicks_order: Option<u32>,
    pub corners_and_indirect_freekicks_text: String,
    pub direct_freekicks_order: Option<u32>,
    pub direct_freekicks_text: String,
    pub penalties_order: Option<u32>,
    pub penalties_text: String,
    pub expected_goals_per_90: f32,
    pub saves_per_90: f32,
    pub expected_assists_per_90: f32,
    pub expected_goal_involvements_per_90: f32,
    pub expected_goals_conceded_per_90: f32,
    pub goals_conceded_per_90: f32,
    pub clean_sheets_per_90: f32,
    pub starts_per_90: f32,
    pub now_cost_rank: u32,
    pub now_cost_rank_type: u32,
    pub form_rank: u32,
    pub form_rank_type: u32,
    pub points_per_game_rank: u32,
    pub points_per_game_rank_type: u32,
    pub selected_rank: u32,
    pub selected_rank_type: u32,
    pub birth_date: String,
    pub region: Option<u32>,
    pub team_join_date: Option<String>,
    pub known_name: Option<String>,
    pub removed: bool,
    pub opta_code: String,
    pub has_temporary_code: bool,
    pub can_select: bool,
    pub can_transact: bool,
    pub tackles: u32,
    pub recoveries: u32,
    pub clearances_blocks_interceptions: u32,
    pub defensive_contribution: String,
    pub defensive_contribution_per_90: f32,
    pub scout_risks: Vec<serde_json::Value>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GameSettings {
    pub league_join_private_max: u32,
    pub league_join_public_max: u32,
    pub league_max_size_public_classic: u32,
    pub league_max_size_public_h2h: u32,
    pub league_max_size_private_h2h: u32,
    pub league_max_ko_rounds_private_h2h: u32,
    pub league_prefix_public: String,
    pub league_points_h2h_win: u32,
    pub league_points_h2h_lose: u32,
    pub league_points_h2h_draw: u32,
    pub league_ko_first_instead_of_random: bool,
    pub cup_start_event_id: Option<u32>,
    pub cup_stop_event_id: Option<u32>,
    pub cup_qualifying_method: Option<String>,
    pub cup_type: Option<String>,
    pub featured_entries: Vec<u32>,
    pub element_sell_at_purchase_price: bool,
    pub percentile_ranks: Vec<u32>,
    pub underdog_differential: u32,
    pub squad_squadplay: u32,
    pub squad_squadsize: u32,
    pub squad_special_min: Option<u32>,
    pub squad_special_max: Option<u32>,
    pub squad_team_limit: u32,
    pub squad_total_spend: u32,
    pub ui_currency_multiplier: u32,
    pub ui_use_special_shirts: bool,
    pub ui_special_shirt_exclusions: Vec<u32>,
    pub stats_form_days: u32,
    pub sys_vice_captain_enabled: bool,
    pub transfers_cap: u32,
    pub transfers_sell_on_fee: f32,
    pub max_extra_free_transfers: u32,
    pub league_h2h_tiebreak_stats: Vec<String>,
    pub timezone: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Phase {
    pub id: u32,
    pub name: String,
    pub start_event: u32,
    pub stop_event: u32,
    pub highest_score: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ElementStat {
    pub label: String,
    pub name: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct ElementType {
    pub id: u32,
    pub plural_name: String,
    pub plural_name_short: String,
    pub singular_name: String,
    pub singular_name_short: String,
    pub squad_select: u32,
    pub squad_min_select: Option<u32>,
    pub squad_max_select: Option<u32>,
    pub squad_min_play: u32,
    pub squad_max_play: u32,
    pub ui_shirt_specific: bool,
    pub sub_positions_locked: Vec<u32>,
    pub element_count: u32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Chip {
    pub id: u32,
    pub name: String,
    pub number: u32,
    pub start_event: u32,
    pub stop_event: u32,
    pub chip_type: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GameConfig {
    pub settings: GameConfigSettings,
    pub rules: serde_json::Value,
    pub scoring: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GameConfigSettings {
    pub entry_per_event: bool,
    pub timezone: String,
}
